[project]
name = "neuropacetools"
version = "0.1.0"
description = "neuropacetools"
authors = [{name = "Ankit N. Khambhati", email = "akhambhati@gmail.com"}]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/khambhati-lab/python-neuropacetools"
repository = "https://github.com/khambhati-lab/python-neuropacetools"
documentation = "https://python-neuropacetools.readthedocs.io"
packages = [
  { include = "neuropacetools", from = "src" },
]
classifiers = [
  "Development Status :: 2 - Alpha",
]
requires-python = ">=3.13"
dependencies = [
    "baseobjects",
    "blockobjects",
    "classversioning",
    "dspobjects",
    "proxyarrays",
    "h5py>=3.14.0",
    "hdf5objects",
    "numpy>=2.3.2",
    "sqlalchemy>=2.0.43",
    "sqlalchemyobjects",
    "cdfs",
    "mxbids"
]

[tool.uv.sources]
proxyarrays = { git = "ssh://git@github.com/AnthonyTechnologies/python-proxyarrays.git", branch = "v0.7.0"}
baseobjects = { git = "ssh://git@github.com/AnthonyTechnologies/python-baseobjects.git", branch = "v1.12.0"}
classversioning = { git = "ssh://git@github.com/AnthonyTechnologies/python-classversioning.git" }
hdf5objects = { git = "ssh://git@github.com/AnthonyTechnologies/python-hdf5objects.git", branch = "v0.6.0"}
blockobjects = { git = "ssh://git@github.com/AnthonyTechnologies/python-blockobjects.git", branch = "v0.1.0"}
dspobjects = { git = "ssh://git@github.com/AnthonyTechnologies/python-dspobjects.git" }
sqlalchemyobjects = { git = "ssh://git@github.com/AnthonyTechnologies/python-sqlalchemyobjects.git", branch = "v0.1.0"}
cdfs = { git = "ssh://git@github.com/AnthonyTechnologies/python-cdfs.git", branch = "v0.4.0"}
mxbids = { git = "ssh://git@github.com/AnthonyTechnologies/python-mxbids.git", branch = "v0.3.0"}

[dependency-groups]
dev = [
    "ipython>=9.4.0",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
